### ISSUE TITLE
this.options() deprecated

### ISSUE THREAD

**Issue by jseverse** [BrightcoveOS/videojs-ga-videocloud#19]
Hello, 
I am trying to implement this with our website brightcove videos. I am getting this warning:
index.min.js:9 VIDEOJS: WARN: this.options() has been deprecated and will be moved to the constructor in 6.0
Could you help please? Thank you.
Josh

**Comment by kfairris** [comment]
@jseverse I found [this fix](https://github.com/devkinetic/videojs-ga/commit/a1449550a342c8ec10c5e1d1630a6f158b1fac17) on Github.  Did you ever find a solution?

**Comment by jseverse** [comment]
@kfairris,
Thank you. Yes, that is the solution I went with. Sorry, I should have updated this. 
Josh

**Comment by mister-ben** [comment]
Latest version now does not log the warning
