### ISSUE TITLE
player broken on Brightcove side

### ISSUE THREAD

**Issue by grahamix** [BrightcoveOS/videojs-ga-videocloud#20]
I'm not sure if anyone else has seen this...   we have been using the plugin successfully for about 3 months. This week - with no changes to the player - new videos on Brightcove cannot be added to our player.  Making copies of the player fails too as it says that the videojs.ga.videocloud.js is missing. Its not!  We've tried uploading the file again with a new name, that fails too.  Old videos using the player still work, and they are still sending GA event data.  We've opened a ticket with Brightcove, but we're a bit stuck.   

An example of a working player can be found here:  https://www.lawsociety.org.uk/support-services/advice/articles/suspicious-activity-reporting/

The JS can be found here: https://www.lawsociety.org.uk/site/static/js/videojs.ga.videocloud.js

Here is event data being sent 

> Account ID               : UA-1664104-17
> Page Title               : Suspicious Activity Reporting - The Law Society
> Host Name                : www.lawsociety.org.uk
> Page                     : /support-services/advice/articles/suspicious-activity-reporting/
> Referring URL            : -
> Hit ID                   : 293577148
> Hit Type                 : event
> Event Name               : Brightcove Player
> Event Type               : Media Play
> Event Label              : 5820547395001 | AML-SARs
> Event Value              : 577
> Non-Interaction          : 1

Attached is a screenshot of the error you get when trying to publish a video using the Advanced embed option
![brightcove-plugin-error](https://user-images.githubusercontent.com/922669/46484307-6cba6200-c7f1-11e8-8693-5659dfea72c6.png)

I will update here if we find out what's gone wrong.

**Comment by mister-ben** [comment]
That's not an issue with the plugin itself but with retrieving the file from your server. You can use the unpkg.com hosted URL https://unpkg.com/videojs-ga-videocloud/dist/videojs.ga.videocloud.min.js

**Comment by grahamix** [comment]
Thanks for that.  Our certificate had renewed and while it presents without problems in all the browsers we've tested with, there is a missing intermediate chain certificate, so SSL is broken for some server-side apps. Including Brightcove.  So it works with plain old HTTP but not HTTPS.  Until we get this resolved, will use the unpkg version. Thanks!
