### ISSUE TITLE
InPlayer Vidpic loading issue

### ISSUE THREAD

**Issue by Rafi-B** [BrightcoveOS/videojs-ga-videocloud#7]
Hi,
We are using the plugin on Brightcove Ver. 1.14.30.
We are experiencing an issue where the inplayer VidPic isn't loading (or taking a very long time to load). User can't see a play button as all you see is a black screen.
When we remove ga from JSON, the vidpic shows up instantly. 
Any idea how to resolve?

Thanks,
-R

**Comment by mister-ben** [comment]
What is a "VidPic"? The poster image?

Can you provide a url to a minimal test case?

**Comment by Rafi-B** [comment]
Hi, thanks for the fast response.
Yes, it's the image that loads before you tap play.
If you go to the following page on desktop you will be able to see the image, but on your iPhone it will not come up. At least on the 5S and 6 that I've tested on iOS 8.4 and 9.2.1

players.brightcove.net/1242911076001/f55b7d8a-9651-4c6f-8b26-bf81e3b6a2af_default/index.html?videoId=ref:title_165597

**Comment by mister-ben** [comment]
You have an older version of the plugin script. A copy of your player with the current version of videojs.ga.videocloud.min.js works.

**Comment by Rafi-B** [comment]
Thanks, I'll do that. Can you point me to right page to get the latest.
https://github.com/mickey/videojs-ga
Or
https://github.com/BrightcoveOS/videojs-ga-videocloud

**Comment by mister-ben** [comment]
https://github.com/BrightcoveOS/videojs-ga-videocloud/blob/master/dist/videojs.ga.videocloud.min.js

mickey/videojs-ga is the original plugin for video.js, from which this was forked. This fork adds functionality specific to the Brightcove Player in Video Cloud, primarily that video ids get tracked into Google Analytics and compatibility with the iframe embed.

**Comment by Rafi-B** [comment]
Great, we'll give it a try. Much appreciated.

**Comment by Rafi-B** [comment]
That worked, Thanks a lot.
