### ISSUE TITLE
Empty 'Event Label'

### ISSUE THREAD

**Issue by boothb81** [BrightcoveOS/videojs-ga-videocloud#8]
Hi Ben- The 'Event Label' is not being populated with the video ID and video title. Did Brightcove roll-out a change. Any ideas?

**Comment by mister-ben** [comment]
Nothing has changed. Do you have an example to look at?

**Comment by boothb81** [comment]
Sorry, no, this is on an internal server. It's working locally on my machine, but not on a server. I'm guessing that I have a timing issue.
